### ISSUE TITLE
unstable unit not found

### ISSUE THREAD

**Issue by foxnudt** [pmiklos/obyte-devnet#11]
![image](https://user-images.githubusercontent.com/17670742/36061802-d1d861ac-0e9a-11e8-9a6e-31e0cf497111.png)

when i ran my witness, the error came, can anyone help me?

**Comment by pmiklos** [comment]
I am closing this since Tony fixed this error about two weeks ago. See https://github.com/byteball/byteballcore/commit/d6f72867a942587fab5c2e9c43d339d6a85eae22
