### ISSUE TITLE
witness down sometimes

### ISSUE THREAD

**Issue by foxnudt** [pmiklos/obyte-devnet#13]
when i try use my wallet to send a transaction ,the witness down, but the transaction can still be confirmed.
![image](https://user-images.githubusercontent.com/17670742/37031935-bf41a118-217b-11e8-963c-32541d5de338.png)

**Comment by pmiklos** [comment]
The witness sends emails in case of certain erroneous situations happen. In the docker version I simply mocked the sendmail program and print the message on the stdout: https://github.com/pmiklos/byteball-devnet/blob/e69d0da44739fdf91d45ee8bdfaa7d1f4cead453/Dockerfile#L7

if you run the devnet on your laptop make sure you have sendmail installed. Also set the `admin_email` and `from_email` in the witness's `conf.json` (under your `~/.config/byteball-devnet-witness` folder). I simply set those with a dummy value so the witness doesn't fail at startup, see https://github.com/pmiklos/byteball-devnet/blob/e69d0da44739fdf91d45ee8bdfaa7d1f4cead453/witness/conf.js#L18
