### ISSUE TITLE
there are no funded addresses

### ISSUE THREAD

**Issue by foxnudt** [pmiklos/obyte-devnet#15]
I extended the number of witnesses to 12 and  generated the genesis unit which assigned some bytes to all the 12 witnesses and the second unit which was for blackbytes. After the hub and all the 12 witnesses were on,  i tried to use a witness to send some bytes to my wallet, the "no funded addresses" error came.
![image](https://user-images.githubusercontent.com/17670742/38164562-2669ac16-3539-11e8-8c46-7baf0bf84740.png)

I don't know why this happens......

**Comment by foxnudt** [comment]
i checked the explorer and found that all the units from the witnesses were unstable except for the genesis unit. it is obvious that some units(unit 2,3,4,5) had more 7 conformations from the witnesses, why weren't they stable?

**Comment by pmiklos** [comment]
did you include all witnesses in the genesis unit as authors?

**Comment by foxnudt** [comment]
you mean the 'paying_adresses' or the 'singer'? I just changed the 'witnesses' and the 'outputs'
![wx20180402-090111](https://user-images.githubusercontent.com/17670742/38179317-6f23e680-3654-11e8-91a1-2ca11be6dd46.png)

**Comment by pmiklos** [comment]
the genesis unit has to be authored by all witnesses and also it must have all 12 as witnesses. So add all of them to the `witnesses` field and  the `paying_addresses` field (I think :) ). If you post your units with 12 witnesses but the the genesis has only 1, then your transactions aren't compatible since in order to find a parent tx there must be only 1 difference in the list of witnesses.

**Comment by foxnudt** [comment]
this is my genesis.js, and address of the witness on which i ran "npm run genesis" is '2BHAF77HJ6HDHPE4DFQCTSFFGJ2DYCEF'
![wx20180402-103049](https://user-images.githubusercontent.com/17670742/38180677-06f9b122-3661-11e8-8d2d-defc67fea4ff.png)

and got this error
![wx20180402-103509](https://user-images.githubusercontent.com/17670742/38180772-91625152-3661-11e8-8bd1-589e0b9dbfdd.png)

**Comment by foxnudt** [comment]
![wx20180402-104012](https://user-images.githubusercontent.com/17670742/38180894-424880ae-3662-11e8-8962-a7fdef948fa4.png)
it seems that only needs one address to unlock this payment.......

**Comment by foxnudt** [comment]
I tried to find the answer in byteball explorer but  could't open the link to the genesis unit of byteball 
https://explorer.byteball.org/#oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=

**Comment by foxnudt** [comment]
"If you post your units with 12 witnesses but the the genesis has only 1, then your transactions aren't compatible since in order to find a parent tx there must be only 1 difference in the list of witnesses."

i think maybe i made you confused. in this situation, all the witness can only issue one unit and after that they didn't have enough money to issue another one. 
![wx20180402-112301](https://user-images.githubusercontent.com/17670742/38181930-73badb5e-3668-11e8-80f2-84655e45bf6a.png)

![wx20180402-112618](https://user-images.githubusercontent.com/17670742/38181964-b5477550-3668-11e8-9b24-85cdb89c4c7e.png)

**Comment by pmiklos** [comment]
yeah, the livenet explorer doesn't show the genesis unit, it fails with 502 Bad Gateway. However, querying the database, `unit_authors` and `unit_witnesses`:

```
sqlite> select  * from unit_authors where unit='oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=';
unit                                          address                           definition_chash                  _mci      
--------------------------------------------  --------------------------------  --------------------------------  ----------
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  BVVJ2K7ENPZZ3VYZFWQWK7ISPCATFIW3  BVVJ2K7ENPZZ3VYZFWQWK7ISPCATFIW3  0         
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  DJMMI5JYA5BWQYSXDPRZJVLW3UGL3GJS  DJMMI5JYA5BWQYSXDPRZJVLW3UGL3GJS  0         
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  FOPUBEUPBC6YLIQDLKL6EW775BMV7YOH  FOPUBEUPBC6YLIQDLKL6EW775BMV7YOH  0         
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  GFK3RDAPQLLNCMQEVGGD2KCPZTLSG3HN  GFK3RDAPQLLNCMQEVGGD2KCPZTLSG3HN  0         
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  H5EZTQE7ABFH27AUDTQFMZIALANK6RBG  H5EZTQE7ABFH27AUDTQFMZIALANK6RBG  0         
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  I2ADHGP4HL6J37NQAD73J7E5SKFIXJOT  I2ADHGP4HL6J37NQAD73J7E5SKFIXJOT  0         
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  JEDZYC2HMGDBIDQKG3XSTXUSHMCBK725  JEDZYC2HMGDBIDQKG3XSTXUSHMCBK725  0         
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  JPQKPRI5FMTQRJF4ZZMYZYDQVRD55OTC  JPQKPRI5FMTQRJF4ZZMYZYDQVRD55OTC  0         
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  OYW2XTDKSNKGSEZ27LMGNOPJSYIXHBHC  OYW2XTDKSNKGSEZ27LMGNOPJSYIXHBHC  0         
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  S7N5FE42F6ONPNDQLCF64E2MGFYKQR2I  S7N5FE42F6ONPNDQLCF64E2MGFYKQR2I  0         
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  TKT4UESIKTTRALRRLWS4SENSTJX6ODCW  TKT4UESIKTTRALRRLWS4SENSTJX6ODCW  0         
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  UENJPVZ7HVHM6QGVGT6MWOJGGRTUTJXQ  UENJPVZ7HVHM6QGVGT6MWOJGGRTUTJXQ  0 
```

```
sqlite> select  * from unit_witnesses where unit='oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=';
unit                                          address                         
--------------------------------------------  --------------------------------
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  BVVJ2K7ENPZZ3VYZFWQWK7ISPCATFIW3
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  DJMMI5JYA5BWQYSXDPRZJVLW3UGL3GJS
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  FOPUBEUPBC6YLIQDLKL6EW775BMV7YOH
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  GFK3RDAPQLLNCMQEVGGD2KCPZTLSG3HN
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  H5EZTQE7ABFH27AUDTQFMZIALANK6RBG
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  I2ADHGP4HL6J37NQAD73J7E5SKFIXJOT
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  JEDZYC2HMGDBIDQKG3XSTXUSHMCBK725
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  JPQKPRI5FMTQRJF4ZZMYZYDQVRD55OTC
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  OYW2XTDKSNKGSEZ27LMGNOPJSYIXHBHC
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  S7N5FE42F6ONPNDQLCF64E2MGFYKQR2I
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  TKT4UESIKTTRALRRLWS4SENSTJX6ODCW
oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=  UENJPVZ7HVHM6QGVGT6MWOJGGRTUTJXQ
``` 

Someone else also experimented with setting up multiple witnesses for the devnet. Let me try to find his repo.

**Comment by pmiklos** [comment]
check this one: https://github.com/iamliqiang/byteball-testnet-bulider/blob/master/bgenesis.js

**Comment by foxnudt** [comment]
it works！！！
