### ISSUE TITLE
[Docker]  Version  Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by LowLowCoder-Mel** [pmiklos/obyte-devnet#18]
CMD:  docker run -it -p 6611:6611 -p 6612:6612 -p 8080:8080 byteball-devnet
OS: Mac
Error:
Wed Aug 01 2018 03:29:32 GMT+0000 (UTC): objMyPermanentDeviceKey not set yet, can't log in
Wed Aug 01 2018 03:29:32 GMT+0000 (UTC): RECEIVED ["justsaying",{"subject":"version","body":{"protocol_version":"1.0dev","alt":"3","library":"byteballcore","library_version":"0.2.92","program":"byteball-devnet-hub","program_version":"1.0.0"}}] from ws://localhost:6611
/root/node_modules/byteballcore/network.js:1961
	var arr = version.split('.');
	                  ^

TypeError: Cannot read property 'split' of undefined
    at version2int (/root/node_modules/byteballcore/network.js:1961:20)
    at handleJustsaying (/root/node_modules/byteballcore/network.js:1993:84)
    at WebSocket.onWebsocketMessage (/root/node_modules/byteballcore/network.js:2726:11)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver.ontext (/root/node_modules/ws/lib/WebSocket.js:841:10)
    at /root/node_modules/ws/lib/Receiver.js:536:18
    at /root/node_modules/ws/lib/Receiver.js:368:7
    at /root/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:454:3)
/root/node_modules/byteballcore/network.js:1961
	var arr = version.split('.');

**Comment by ly95** [comment]
same

**Comment by pmiklos** [comment]
the old byteball libraries didn't work very well with devnet last year. I migrated the project to the latest Obyte libraries recently, it seemed to work well for me without any patches. Also, this time I checked in a package-lock.json to lock down the dependencies. Previously, the latest git version of byteball libraries were used which might have contained all kinds of unstable stuff.

**Comment by pmiklos** [comment]
actually I remember this version.split() error when migrating to the new libraries. I had to update the [config/constants.js](../blob/master/config/constants.js) to include .`minCoreVersion`
