### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by madeshv5543** [pmiklos/obyte-devnet#22]
RECEIVED ["justsaying",{"subject":"version","body":{"alt":"3","library":"ocore","library_version":"0.2.95","program":"obyte-devnet-hub","program_version":"1.0.0"}}] from ws://localhost:6611
/home/ubuntu/obyte-devnet/node_modules/ocore/network.js:2070
                        if (constants.supported_versions.indexOf(body.protocol_version) === -1){
                                                         ^

TypeError: Cannot read property 'indexOf' of undefined
    at handleJustsaying (/home/ubuntu/obyte-devnet/node_modules/ocore/network.js:2070:37)
    at WebSocket.onWebsocketMessage (/home/ubuntu/obyte-devnet/node_modules/ocore/network.js:3008:11)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at Receiver.ontext (/home/ubuntu/obyte-devnet/node_modules/ws/lib/WebSocket.js:841:10)
    at /home/ubuntu/obyte-devnet/node_modules/ws/lib/Receiver.js:536:18
    at /home/ubuntu/obyte-devnet/node_modules/ws/lib/Receiver.js:368:7
    at /home/ubuntu/obyte-devnet/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:464:3)
    at onwrite (_stream_writable.js:455:7)

npm ERR! Linux 4.15.0-1043-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--prefix" "witness" "run" "genesis"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! obyte-devnet-witness@1.0.0 genesis: `node genesis.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the obyte-devnet-witness@1.0.0 genesis script 'node genesis.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the obyte-devnet-witness package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node genesis.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs obyte-devnet-witness
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls obyte-devnet-witness
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/obyte-devnet/npm-debug.log

npm ERR! Linux 4.15.0-1043-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "genesis"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! obyte-devnet@1.0.0 genesis: `npm --prefix witness run genesis`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the obyte-devnet@1.0.0 genesis script 'npm --prefix witness run genesis'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the obyte-devnet package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm --prefix witness run genesis
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs obyte-devnet
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls obyte-devnet
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/obyte-devnet/npm-debug.log

**Comment by pmiklos** [comment]
Merged latest changes with autonomous agents support. The above error is now fixed in the ocore library
